version: '3'
services:
  vizrelay:
    build: .
    ports:
      - "5000:5000"
    environment:
      - RELAY_CONFIG_JSON={"neuroglancer":{"base_url":"http://localhost:8002"}}
  render:
    image: fcollman/render-ws
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTIONS="-Xms1024m -Xmx1024m -server -Djava.awt.headless=true"
      - MONGO_HOST=mongodb.host
      - MONGO_PORT=27017
      - NDVIZ_URL="localhost:5000"
  ndviz:
    image: neurodata/ndviz
    ports:
      - "8002:8080"
